server:
  port: 8090

#mysql setting 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-324o8d-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp!@#123	

#mybatis setting
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml
